apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: helloworld-toleration-ds
  labels:
    app: helloworld-toleration
spec:
  selector:
    matchLabels:
      app: helloworld-toleration
  template:
    metadata:
      labels:
        app: helloworld-toleration
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web
        imagePullPolicy: IfNotPresent
        ports:
        - name: node-port
          containerPort: 80
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
